# Copyright 2019 The OpenSDS Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# Defines deployment design and assigns role to server groups
- hosts:
  - controllers
  gather_facts: true
  any_errors_fatal: true
  become: True
  
# Defines deployment design and assigns role to server groups
- name: Install keystone services
  hosts: controllers
  remote_user: root
  vars_files:
    - group_vars/common.yml
    - group_vars/auth.yml
  gather_facts: false
  become: True
  tasks:
    - import_role:
        name: auth-installer
  tags: keystone

- name: Install delfin
  hosts: controllers
  remote_user: root
  vars_files:
    - group_vars/common.yml
    - group_vars/delfin.yml
  gather_facts: false
  become: True
  tasks:
    - import_role:
        name: delfin-installer
  tags: delfin

- name: Install SRM Toolchain
  hosts: controllers
  remote_user: root
  vars_files: 
    - group_vars/common.yml
    - group_vars/delfin.yml
    - group_vars/srm-toolchain.yml
  gather_facts: false
  become: True
  tasks:
    - import_role:
        name: srm-toolchain-installer
      when:
        - install_srm_toolchain == true
  tags: srm_toolchain

- name: deploy dashboard
  hosts: controllers
  remote_user: root
  vars_files:
    - group_vars/common.yml
    - group_vars/auth.yml
    - group_vars/srm-toolchain.yml
    - group_vars/dashboard.yml
  gather_facts: false
  become: True
  tasks:
    - include_role:
        name: dashboard-installer
      when:
        - enable_dashboard == true
  tags: dashboard
