name: Delfin CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 6
      matrix:
        platform:
          - ubuntu-16.04
          - ubuntu-18.04
        python-version: [ 3.6, 3.7, 3.8 ]

    steps:
      - uses: actions/checkout@v2
      - name: Install Python version ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test-requirements.txt
          pip install tox codecov
      - name: Unit test with tox
        run: tox
      - name: Test coverage with  codecov
        run: codecov
